### ISSUE TITLE
加载失败，网络错误

### ISSUE THREAD

**Issue by rainbye** [1715173329/UnblockNeteaseMusic#1178]
### Bug 描述

加载失败，网络错误

### 日志内容

 sudo     node app.js -p 80:443 -f 59.111.181.38  
[sudo] vae 的密码： 
INFO: (app) HTTP Server running @ http://0.0.0.0:80
INFO: (app) HTTPS Server running @ http://0.0.0.0:443
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
INFO: (provider/match) Replaced: [1962166937] 等你下课
    audioId: 1962166937
    songName: "等你下课"
    url: "http://upos-sz-mirrorhw.bilivideo.com/ugaxcode/i180203ws1my9y33l6g8c76u1q117es9-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1690105912&gen=playurlv2&os=hwbv&oi=2084574796&trid=59969dc999584b53b61ede0122d36e03B&mid=0&platform=pc&upsig=f7ef645ff0dfd6cfda70425e51f7e85d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
INFO: (provider/match) Replaced: [1962165963] 说好不哭
    audioId: 1962165963
    songName: "说好不哭"
    url: "http://upos-sz-mirrorhw.bilivideo.com/ugaxcode/m210208a22sldc817guf9g1tmgof7a1t-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1690105915&gen=playurlv2&os=hwbv&oi=2084574796&trid=d42e4c9e49d1412b9d5ca70f05eb763eB&mid=0&platform=pc&upsig=696617dc6ae9e0c472ea4cb2ce4dddb2&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
INFO: (provider/match) Replaced: [1962166119] 倒影
    audioId: 1962166119
    songName: "倒影"
    url: "http://upos-sz-mirrorhw.bilivideo.com/ugaxcode/n221007a22iqnhcugax74d19s38jg7q2-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1690105917&gen=playurlv2&os=hwbv&oi=2084574796&trid=39fdb3235ed142cbb54fb0f95e2ae198B&mid=0&platform=pc&upsig=23dbed7dec7eeca4e191d92614a28962&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at new i (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:5418)
        at p (/home/vae/UnblockNeteaseMusic/precompiled/app.js:3:39467)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
INFO: (provider/match) Replaced: [1962166915] 错过的烟火
    audioId: 1962166915
    songName: "错过的烟火"
    url: "http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/n220715qn3d2hi9n7whjwr3p21pc4d5t-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1690105919&gen=playurlv2&os=cosbv&oi=2084574796&trid=a74b8f174d804a7188dfd660b03d3578B&mid=0&platform=pc&upsig=ab98dd608a0fbd41e38bae4add450e0e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"

### 网易云音乐版本号

1.0

### 操作系统

ubuntu

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by chen310** [comment]
下载安装 `yt-dlp`，或者移除 `ytdlp` 这个音源

**Comment by rainbye** [comment]
用了0.27.1的版本，用migu可以了，但是周杰伦的mv放不出来。

**Comment by rainbye** [comment]
> 下载安装 `yt-dlp`，或者移除 `ytdlp` 这个音源

安装了后来
