### ISSUE TITLE
最新版源码出现大量报错，以及无法点赞评论

### ISSUE THREAD

**Issue by a6513375** [1715173329/UnblockNeteaseMusic#118]
如题
点赞后出现 操作失败 报错
![IMG](https://user-images.githubusercontent.com/52791712/130324853-64edba62-9bce-4a33-bee1-0a6b33b97ecd.png)

相关日志：
`MITM > interface.music.163.com
TUNNEL > ac.dun.163yun.com:443
ISHOST > Found malformed URL interface.music.163.com. We use the fallback method.
ISHOST > Please report this to us.
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:561:9)
    at new URL (node:internal/url:637:5)
    at isHost (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\utilities.js:10:16)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:100:4
    at Array.some (<anonymous>)
    at Object.hook.request.before (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:99:36)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\server.js:34:31 {
  input: 'interface.music.163.com',
  code: 'ERR_INVALID_URL'
}
MITM > interface.music.163.com
ISHOST > Found malformed URL interface.music.163.com. We use the fallback method.
ISHOST > Please report this to us.
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:561:9)
    at new URL (node:internal/url:637:5)
    at isHost (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\utilities.js:10:16)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:100:4
    at Array.some (<anonymous>)
    at Object.hook.request.before (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:99:36)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\server.js:34:31 {
  input: 'interface.music.163.com',
  code: 'ERR_INVALID_URL'
}
MITM > interface.music.163.com
ISHOST > Found malformed URL interface.music.163.com. We use the fallback method.
ISHOST > Please report this to us.
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:561:9)
    at new URL (node:internal/url:637:5)
    at isHost (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\utilities.js:10:16)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:100:4
    at Array.some (<anonymous>)
    at Object.hook.request.before (E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\hook.js:99:36)
    at E:\Software\UnblockNeteaseMusic-master\core\UnblockNeteaseMusic-enhanced\src\server.js:34:31 {
  input: 'interface.music.163.com',
  code: 'ERR_INVALID_URL'
}
MITM > interface.music.163.com`

**Comment by 4860575** [comment]
错误满屏
MITM > music.163.com (ssl)
ISHOST > Found malformed URL music.163.com. We use the fallback method.
ISHOST > Please report this to us.
TypeError [ERR_INVALID_URL]: Invalid URL: music.163.com
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at isHost (/root/UnblockNeteaseMusic/src/utilities.js:10:16)
    at /root/UnblockNeteaseMusic/src/hook.js:100:4
    at Array.some (<anonymous>)
    at Object.hook.request.before (/root/UnblockNeteaseMusic/src/hook.js:99:36)
    at /root/UnblockNeteaseMusic/src/server.js:34:31 {
  input: 'music.163.com',
  code: 'ERR_INVALID_URL'
}

**Comment by pan93412** [comment]
前者已修正；後者已經確定，但是不知道怎麼修⋯⋯ 先標成 `help wanted`

**Comment by vcheckzen** [comment]
Windows10 这样启动可以点赞评论，无法签到

```shell
node app.js -p 6666:6667 -s -e https://music.163.com -f 59.111.19.33
```

**Comment by 1715173329** [comment]
网易云音乐 Windows 版本 2.5.0，目前可正常点赞和签到。

**Comment by byludy** [comment]
![image](https://user-images.githubusercontent.com/56289598/132978061-c622d2f0-5cc5-4402-8222-835b73462f26.png)
![image](https://user-images.githubusercontent.com/56289598/132978076-594e0cdd-86df-4b1d-9ddb-cf28f2c4bddd.png)
不能点赞
2.8.0

**Comment by 1715173329** [comment]
用这个版本：
https://transfer.sh/iXvkT5/CloudMusic.zip
