### ISSUE TITLE
Linux版本0.27.4-arm64无法运行

### ISSUE THREAD

**Issue by gavin8282** [1715173329/UnblockNeteaseMusic#1232]
### Bug 描述
下载“https://github.com/UnblockNeteaseMusic/server/releases/download/v0.27.4/unblockneteasemusic-linux-arm64”
重命名为“ UnblockNeteaseMusic”
UnblockNeteaseMusic -v
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/snapshot/UnblockNeteaseMusic/precompiled/app.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0

### 启动命令及环境变量

/usr/bin/UnblockNeteaseMusic -o pyncmd kuwo kugou -p 6200:6201 -s >>/tmp/mp3.log 2>&1 &

### 日志内容

Error: Cannot find module '/snapshot/UnblockNeteaseMusic/precompiled/app.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### 网易云音乐版本号

版本2.3.8 (878)

### 操作系统

ubuntu 22.04

### 其他信息

使用[Actions](https://github.com/UnblockNeteaseMusic/server/actions)的“infra(package): release v0.27.4 #1220”版本也是0.27.4是可以运行的
### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
已经重新上传了
