### ISSUE TITLE
打开后闪退

### ISSUE THREAD

**Issue by Harrydi2006** [1715173329/UnblockNeteaseMusic#138]
使用最新的exe程序和最新的node，双击打开后短暂显示黑框后关闭

**Comment by 1715173329** [comment]
检测 8080 端口是否被占用。

**Comment by pan93412** [comment]
建議把 exe 拖曳到 cmd 上面執行，這樣錯誤訊息會比較明顯。

**Comment by Harrydi2006** [comment]
HTTP Server running @ http://0.0.0.0:8080
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:8081
    at Server.setupListenHandle [as _listen2] (net.js:1303:21)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at C:\snapshot\UnblockNeteaseMusic\src\app.js
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1347:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8081
}

**Comment by pan93412** [comment]
> HTTP Server running @ http://0.0.0.0:8080
> events.js:352
> throw er; // Unhandled 'error' event
> ^
> 
> Error: listen EACCES: permission denied 0.0.0.0:8081
> at Server.setupListenHandle [as _listen2] (net.js:1303:21)
> at listenInCluster (net.js:1368:12)
> at Server.listen (net.js:1454:7)
> at C:\snapshot\UnblockNeteaseMusic\src\app.js
> Emitted 'error' event on Server instance at:
> at emitErrorNT (net.js:1347:8)
> at processTicksAndRejections (internal/process/task_queues.js:82:21) {
> code: 'EACCES',
> errno: -4092,
> syscall: 'listen',
> address: '0.0.0.0',
> port: 8081
> }

試試看用管理員權限啟動？或者是你建立捷徑，並在啟動參數後面加上 `-p 你想要的port:你想要的第二個port`。

**Comment by Harrydi2006** [comment]
应该是端口冲突，改成52000就好了
